inputs:
  cluster_name:
    type: string
    default: home-tap-nnn
    description: The Name of the cluster
    format: ""
  cluster_description:
    type: string
    default: Aria managed cluster
    description: Description of the cluster to be created
  control_plane_replicas:
    type: number
    default: "1"
    description: Controller Plane node count
  worker_node_replicas:
    type: number
    default: "3"
    description: Worker node count
resources:
  TAP_Platform:
    type: Cloud.Terraform.Configuration
    metadata:
      layoutPosition:
        - 0
        - 0
    properties:
      variables:
        username: ${secret.tmc_username}
        password: ${secret.tmc_password}
        provisioner_name: tap
        cluster_name: ${input.cluster_name}
        cluster_description: ${input.cluster_description}
        cluster_group_name: home-tap
        vm_class: best-effort-tap-node
        storage_class: general-usage
        kubernetes_version: v1.26.13+vmware.1-fips.1-tkg.3
        control_plane_replicas: ${input.control_plane_replicas}
        worker_node_replicas: ${input.worker_node_replicas}
        kubelet_disk: 30G
        containerd_disk: 80G
      providers: []
      terraformVersion: 1.0.5
      configurationSource:
        repositoryId: 487ecab4-1138-4210-b821-594a4b2f0e26
        commitId: 0e75410dbfadafd87daedf0e31655b6857cca679
        sourceDirectory: create_cluster_tkgs
